### PR TITLE
Add go 1.13.8

### PR DESCRIPTION
**Pull request by roopakv**

### CODE REVIEW

**Comment by roopakv** [comment]
Seems like i dont have permission to run the workflow.

**Comment by felicianotech** [comment]
@roopakv Hey, thanks for this PR. :+1:

So I didn't open this PR myself because I was waiting for #61 to be merged first. Otherwise it causes a conflict which is what we have now. Before I close this PR and open a new one, would you like to resolve the conflict yourself?

Basically what you'd need to do is rebase this branch on master so that we end up with a single commit in this PR without a git conflict.

**Comment by roopakv** [comment]
Yeah I'll push up a fix now

**Comment by roopakv** [comment]
~in 30 mins rather, if that's ok

**Comment by roopakv** [comment]
@felicianotech updated

**Comment by felicianotech** [comment]
Hey @roopakv I'm sorry but I'm going to just close this PR. It wasn't rebased and the commit message doesn't have the [release] string that it needs.

In the future, the instructions for releasing a new tag for this image is in the readme. It show you how to use the included scripts to automate this process.

**Comment by roopakv** [comment]
Cool! I'll keep that in mind

**Pull request closed without merging**
